### ISSUE TITLE
Add Contribution.md

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [Avdhesh-Varshney/Chanakya-Niti#1]
Hey @Avdhesh-Varshney ,
To streamline the contribution process and make it easier for new contributors to get involved, it's important to have clear and detailed contribution guidelines. A CONTRIBUTING.md file outlines the steps and best practices for contributing to the project, ensuring consistency and high-quality contributions.
Please assign me this issue

**Comment by karishma108** [comment]
I want to work on this issue and I am from a GSSCO'24. please assign me this.

**Comment by Avdhesh-Varshney** [comment]
@Santhosh-Siddhardha @karishma108 this is not required by the project. Just focus on the code part not on non-code part. You can join the discord to discussion about the enhancement of the project and achieve their goals and future scopes.
