### ISSUE TITLE
🧑‍💻:  Add a Navigation bar.

### ISSUE THREAD

**Issue by aapJoysakoi** [Avdhesh-Varshney/chanakya-niti#101]
:red_circle: **Title** : Add a Navigation bar.
:red_circle: **Enhancement Aim** : Enhanced Accessibility and increase in engagement 
:red_circle: **Changes** : Add different sections and various elements through a navigation bar.

***********************************************************************

- Full name :  Joysa Kaushik
- Participant role- SSOC

**Comment by aapJoysakoi** [comment]
Please Assign me this issue under SSOC.

**Comment by Avdhesh-Varshney** [comment]
@aapJoysakoi go ahead.

**Comment by Avdhesh-Varshney** [comment]
@aapJoysakoi what's the update?

**Comment by aapJoysakoi** [comment]
Hey, actually I’ve been a little too occupied in college whole past week.. I’ll resolve the issue by this weekend for sure.

**Comment by Avdhesh-Varshney** [comment]
> Hey, actually I’ve been a little too occupied in college whole past week.. I’ll resolve the issue by this weekend for sure.

But navbar is at the high priority, raise pr within 2 days not more than that.
