### ISSUE TITLE
🧑‍💻: Style to Scrollbar

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/Chanakya-Niti#103]
:red_circle: **Title** :Change Style of Scrollbar
:red_circle: **Enhancement Aim** : To make scrollbar attractive.
:red_circle: **Changes** : Make change in color and give radius to thumb of scrollbar.

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/126322584/09e2ebcb-7bb7-4f7e-83d2-50a46dac3511)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Zala Bhavy
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Miran-Firdausi** [comment]
Can you please assign this to me?

Full name: Miran Firdausi
What is your participant role? Gssoc'24

Thanks!

**Comment by Sneha0019** [comment]
Full Name : Sneha Menat
Participant Role : GSSOC'24
@Avdhesh-Varshney please assign me this task!

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy go ahead.
