### ISSUE TITLE
🧑‍💻: Add Hover effects on Enter button.

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/Chanakya-Niti#106]
:red_circle: **Title** :Add Hover effects on Enter
:red_circle: **Enhancement Aim** :To give better user expererience.
:red_circle: **Changes** : Add Css related to that.

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/126322584/0ca954a2-764e-4e42-92b9-6817dc2ad691)
I will add hover effects on this.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**Zala Bhavy
- Full name : 
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Mallik0** [comment]
kindly assign this issue to me i feel adding a couple of css classes would do the trick and it will be having a really good UI

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy go ahead.
