### ISSUE TITLE
🧑‍💻:  Add List of the episode.

### ISSUE THREAD

**Issue by ronisarkarexe** [Avdhesh-Varshney/Chanakya-Niti#107]
:red_circle: **Title** : Add List of episode
:red_circle: **Enhancement Aim** : Added button View List of Eposode
:red_circle: **Changes** : On the right side of the enter button, there should be another button called "View List." When I click on it, a list of episodes should open on the model or on the right sidebar.

### Screenshots 📷
No

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Add List of the episodes with number.
- What is your participant role? GSSOC, SSOC (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@ronisarkarexe not required. Before creating any issue, you have to gone through for the similar issue.
