### ISSUE TITLE
🧑‍💻: Add Conclusion Of The Chapter.

### ISSUE THREAD

**Issue by PriyanshuValiya** [Avdhesh-Varshney/Chanakya-Niti#108]
:red_circle: **Title** : Conclusion Component.
:red_circle: **Enhancement Aim** : To Get Brief Idea About Chapter.
:red_circle: **Changes** : 

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Priyanshu Valiya
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@PriyanshuValiya how can you approach it? can you explain it to me on discord server? Link is present in project main readme file.

**Comment by Avdhesh-Varshney** [comment]
go ahead.
