### ISSUE TITLE
[FEATURE]: Enter Button missing

### ISSUE THREAD

**Issue by Nirvanjha2004** [Avdhesh-Varshney/Chanakya-Niti#11]
Since there is Enter button...i would like to add an enter button.
![cha](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/140783287/09b034c3-7bfe-4536-8b0a-864237eb3228)

**Comment by Nirvanjha2004** [comment]
Please assign this issue to me

**Comment by Avdhesh-Varshney** [comment]
@Nirvanjha2004 Raise single issue at a time. Assigned to you.
