### ISSUE TITLE
🧑‍💻: Issue Greeting Template

### ISSUE THREAD

**Issue by thevijayshankersharma** [Avdhesh-Varshney/Chanakya-Niti#110]
:red_circle: **Title** :
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** : 

This template provides a structured format for creating greetings on GitHub issues related to enhancements or bug fixes. It includes sections for the title, enhancement aim, proposed changes, optional screenshots, and important information to be mentioned while taking the issue. This standardized template aims to streamline communication and ensure clarity for contributors and maintainers.

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Vijay Shanker Sharma
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
Contributor (GSSOC, SSOC)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@thevijayshankersharma not required.
