### ISSUE TITLE
🧑‍💻:  Section to add favourite episodes

### ISSUE THREAD

**Issue by anvithagowda098** [Avdhesh-Varshney/Chanakya-Niti#111]
:red_circle: **Title** : Section to add favourite episodes
:red_circle: **Enhancement Aim** : Section can be added where users can add their favourite episodes to a separate 'FAVOURITES' folder. A user account page will be necessary.
:red_circle: **Changes** : 

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anvitha
- What is your participant role? (GSSoC'24)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@anvithagowda098 issue already present. For further communication, join the project discord server. Link is present in main readme file.
