### ISSUE TITLE
🐛: Authorization token exposed , sol : authorize token via ENV 

### ISSUE THREAD

**Issue by Sushanth-Hebri** [Avdhesh-Varshney/chanakya-niti#114]
Authorization token is exposed publicly, which is not good. 
Lets take security as priority 
Kindly Assign this task to me under Level 2 of GSSOC'24 
thank you ❤️

**Comment by Avdhesh-Varshney** [comment]
@Sushanth-Hebri go ahead.

**Comment by ROKUMATE** [comment]
Can Your Briefly Explain the Issue ? 
here we just have to Put the AuthToken in environmental variables file or the issue is different ?

**Comment by Avdhesh-Varshney** [comment]
> Can Your Briefly Explain the Issue ? here we just have to Put the AuthToken in environmental variables file or the issue is different ?

Nope, but change the env variable name as i've already mentioned in pr 2 times.

**Comment by ROKUMATE** [comment]
> > Can Your Briefly Explain the Issue ? here we just have to Put the AuthToken in environmental variables file or the issue is different ?
> 
> Nope, but change the env variable name as i've already mentioned in pr 2 times.

ohkok ... If the Issue is then also not solved i would like to work on this issue under GSSOC Contributiion

**Comment by Avdhesh-Varshney** [comment]
@ROKUMATE go ahead.
