### ISSUE TITLE
🧑‍💻: Footer should be added

### ISSUE THREAD

**Issue by PrachiJadhav2310** [Avdhesh-Varshney/chanakya-niti#119]
Footer section should be added at the bottom that also contains conact us info and rights reserved section

**Comment by nishant0708** [comment]
Hey Can I work On This @PrachiJadhav2310

**Comment by M-DEV-1** [comment]
Hi, I'd like to work on this. Please assign this issue to me. Thanks.

**Comment by Avdhesh-Varshney** [comment]
already present #60
