### ISSUE TITLE
Missing Learn.md file

### ISSUE THREAD

**Issue by debangi29** [Avdhesh-Varshney/Chanakya-Niti#12]
Add Learn.md file as instructed by Gssoc guidelines

**Comment by debangi29** [comment]
Please assign me the issue @Avdhesh-Varshney under Gssoc

**Comment by Avdhesh-Varshney** [comment]
@debangi29 As such no guidelines are not provided. So, you are focus on the code part contribution in this repository not on non-code part.

**Comment by debangi29** [comment]
https://www.youtube.com/live/K55HMy7alag?feature=shared

Please check this guide video for Gssoc, from 10:35
Fine, if a non-code part contribution is not welcomed, but please check the guidelines before adding an invalid tag!!
Thanks
