### ISSUE TITLE
UI mistake needed to be corrected

### ISSUE THREAD

**Issue by 05hiteshbansal** [Avdhesh-Varshney/Chanakya-Niti#121]
:red_circle: UI mistake needed to be corrected :
:red_circle: It is looking odd for website :
:red_circle: We can add other ways by removing it and adding a placeholder instead

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/83907989/665430db-58a9-487d-a45e-624de5d70d67)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Hitesh Bansal
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by nishant0708** [comment]
hey can i work on this?

**Comment by Avdhesh-Varshney** [comment]
not required.
