### ISSUE TITLE
🧑‍💻:  Related resources

### ISSUE THREAD

**Issue by Mayureshd-18** [Avdhesh-Varshney/chanakya-niti#122]
:red_circle: **Title** : Related resources
:red_circle: **Enhancement Aim** : Provide links to related books, articles, or videos about Chanakya and his teachings.
:red_circle: **Changes** :  Add links for related resources in the page

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mayuresh 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)GSSOC, SSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Mayureshd-18 it's a good choice. But this time website lacks of a navbar and i'm thinking to create a backend repo to keep these resources apart from front-end. Wait for it and for further communication, join project discord channel.

**Comment by Avdhesh-Varshney** [comment]
completed!
