### ISSUE TITLE
🧑‍💻: remembering playback state

### ISSUE THREAD

**Issue by Mayureshd-18** [Avdhesh-Varshney/Chanakya-Niti#123]
:red_circle: **Title** : remembering playback state
:red_circle: **Enhancement Aim** : To open up the same episode from which the user had closed the window
:red_circle: **Changes** : 
Add a feature that will save the episode number and will open up the same episode when the user opens the website

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mayuresh
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)GSSOC, SSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by nishant0708** [comment]
can i work on this issue

**Comment by Mayureshd-18** [comment]
@nishant0708 Actually I have the prototype ready and started working on the issue. There are still many issues open, you can work on them.
Regards.

**Comment by Avdhesh-Varshney** [comment]
@Mayureshd-18 go ahead.
@nishant0708 raise your own issue and wait for assigning ok.
