### ISSUE TITLE
TimeStams not visible

### ISSUE THREAD

**Issue by Nirvanjha2004** [Avdhesh-Varshney/Chanakya-Niti#13]
The TimeStamps are not clearly visible. I would like to add some Styling to it to make it look better.
![Time](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/140783287/601ef979-283d-42e7-a28c-4b62a15943bd)

**Comment by Nirvanjha2004** [comment]
Please assign this issue to me!

**Comment by Avdhesh-Varshney** [comment]
Already work going on #24
