### ISSUE TITLE
🧑‍💻:  Improve User Interface

### ISSUE THREAD

**Issue by codewithganeshhh** [Avdhesh-Varshney/chanakya-niti#130]
:red_circle: **Title** : Adding Navbar and footer section
:red_circle: **Enhancement Aim** : For More user interaction 
:red_circle: **Changes** :  For Good User Interface and look more professional

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Ganesh Kumar
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
- I am a contributor in GSSOC and SSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by codewithganeshhh** [comment]
Full name : Ganesh Kumar
I am a contributor in GSSOC and SSOC 
I have already created 11 PR in GSSOC and 9 are Merged

**Comment by codewithganeshhh** [comment]
Kindly Assign ME for this @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
@codewithganeshhh go ahead.
