### ISSUE TITLE
🧑‍💻: Give style to input field

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/chanakya-niti#131]
:red_circle: **Title** : Style Input Field
:red_circle: **Enhancement Aim** : Better UI
:red_circle: **Changes** : Give Radius , add some Hover effects.

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/126322584/e09bcb59-54af-4dad-af7c-c6f2bf9d352c)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhavy Zala
- What is your participant role?  Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Please assign me !!

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy assigned to you
