### ISSUE TITLE
🧑‍💻: Add copyright label

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Avdhesh-Varshney/chanakya-niti#133]
:red_circle: **Add copyright labe;** :
:red_circle: **To know who owns copyright** :
:red_circle: **I want to add copyright in the footer** : 

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sai pradyumna
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Saipradyumnagoud** [comment]
@Avdhesh-Varshney  can you please assign me this issue

**Comment by Avdhesh-Varshney** [comment]
@Saipradyumnagoud website not having footer. So, wait for it.

**Comment by Saipradyumnagoud** [comment]
> @Saipradyumnagoud website not having footer. So, wait for it.

i will add footer

**Comment by Avdhesh-Varshney** [comment]
not required. Work either on functional part or ui enhancement part.
