### ISSUE TITLE
🧑‍💻: HomePage Building

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/chanakya-niti#134]
:red_circle: **Title** : Homapage building
:red_circle: **Enhancement Aim** : Building a Homepage of the website
:red_circle: **Changes** : 
- As mentioned in the main readme file about the pathway & structure of the project, design a homepage component for the website.

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/114330097/aee65cee-a0e7-4516-9fd7-b93173d30967)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Sid-80** [comment]
@Avdhesh-Varshney Myself Siddharth,
I am willing to work on this issue under GSSOC24

**Comment by Avdhesh-Varshney** [comment]
@Sid-80 go ahead.

**Comment by Sid-80** [comment]
@Avdhesh-Varshney Hey, any designs ready or I have to design from scratch
