### ISSUE TITLE
🧑‍💻: Designing a shareable card component

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/chanakya-niti#136]
:red_circle: **Title** : creating a shareable card component
:red_circle: **Enhancement Aim** : Designing a card component to showcase the image and attach the link send to the card component which will further use in resources section.

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/114330097/10c82be4-1eab-4a5a-87f1-2f4febe4a18f)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Asymtode712 go ahead.

**Comment by Avdhesh-Varshney** [comment]
@Asymtode712 start working on ui of shared card component present on the website.

**Comment by Asymtode712** [comment]
@Avdhesh-Varshney Sure!!

**Comment by Asymtode712** [comment]
Hey @Avdhesh-Varshney , is this looking good:


https://github.com/Avdhesh-Varshney/chanakya-niti/assets/115717746/b8d96d05-895e-47b1-b304-e48ffa693c0e

Please let me know your suggestions if there are any....

**Comment by Asymtode712** [comment]
@Avdhesh-Varshney Add the glassmorphin effect to the card please check it out and tell me whether it is a fit or not:


https://github.com/Avdhesh-Varshney/chanakya-niti/assets/115717746/aeae9b04-c037-460e-8d98-2923a86333e6

**Comment by Avdhesh-Varshney** [comment]
@Asymtode712 looks good. But don't change the background at now.

**Comment by Asymtode712** [comment]
@Avdhesh-Varshney The background was just for showing the glassmorphin effect.....Should I raise a PR??
