### ISSUE TITLE
🧑‍💻: Contributors page designing

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/chanakya-niti#137]
:red_circle: **Title** : creating contributors page
:red_circle: **Enhancement Aim** : Designing the contributors page to render all the contributors of the website.

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/114330097/bee714c8-0407-409d-9f21-ae355efc0265)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Madhavdua** [comment]
Kindly assign me this issue.
(Madhav dua
SSOC contributor)

**Comment by Avdhesh-Varshney** [comment]
@Madhavdua go ahead.
