### ISSUE TITLE
Daily Wisdom

### ISSUE THREAD

**Issue by MetiUmashri** [Avdhesh-Varshney/chanakya-niti#139]
A feature enhancement here could be that:

A “Daily Wisdom” section that presents a random or scheduled audio clip or quote from Chanakya Neeti.
Push notifications or email subscriptions for daily wisdom.

- Full name: umashri 
- Contributor - SSOC

Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@MetiUmashri i'm confused where should i keep this feature on the website? And mention me your workflow to clarify this idea in my mind. You can discuss with me on discord server.
