### ISSUE TITLE
Enhancing the whole page

### ISSUE THREAD

**Issue by vaishnavip27** [Avdhesh-Varshney/chanakya-niti#140]
The current UI of the page seems to be outdated, unappealing or not aligned with modern web standards which deter users from staying on the site. Important information might be buried or not highlighted properly making it hard for the users to find what they are looking for. I aim to address these problems, imrproving user satisfaction, engagement and overall site performance.

I want to update the visual design to be clean, appealing and aligned with the current website trends

As you can see, because of the current text color of the content, it is difficult for the users to read it in the first go. It should be clearly visible to the users and should be readable.

![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/143169451/da363121-7b39-45af-978c-6d5970b15457)

**Comment by Avdhesh-Varshney** [comment]
@vaishnavip27 i've changed the website structure and fixed the routing. Now if you would like to contribute and desgin chanakya audio page, mention me or you can discuss your query directly on discord server.

Also mention your open source program? It's mandatory.
