### ISSUE TITLE
🧑‍💻: Adding Cursor Animation

### ISSUE THREAD

**Issue by SagarRathore1** [Avdhesh-Varshney/chanakya-niti#141]
:red_circle: **Title** : Adding Cursor Animation
:red_circle: **Enhancement Aim** : To  make website more attractive and professional along with enhancing user experience
:red_circle: **Changes** : I would like to add cursor animation

### Screenshots 📷
![Screenshot 2024-06-17 121136](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/169483518/0f03796f-1984-469d-897f-ce34c8f05684)

https://github.com/Avdhesh-Varshney/chanakya-niti/assets/169483518/b586f238-0f0e-4429-8773-c6b6355091c4

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sagar Rathore
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
- GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ROKUMATE** [comment]
Full Name: Rohit Kumawat 
I want to work on this issue under the GSSOC.

do assign mee so that I could start working on It

**Comment by Avdhesh-Varshney** [comment]
@SagarRathore1 go ahead.
