### ISSUE TITLE
🧑‍💻: Add background animation in header text

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/chanakya-niti#142]
:red_circle: **Title** : Add background animation in header text
:red_circle: **Enhancement Aim** : More attractive UI
:red_circle: **Changes** : CSS

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/126322584/7c4b5209-d401-4a7f-8c00-746ef5ff9cbd)

Here behind this text i will add animations.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhavy Zala
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Please assign me !

**Comment by Avdhesh-Varshney** [comment]
not needed.
