### ISSUE TITLE
🐛: Page is not responsive in mobile view

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Avdhesh-Varshney/chanakya-niti#144]
:red_circle: **Title** : Page is not responsive in mobile view
:red_circle: **Bug** : not responsive in mobile view
:red_circle: **Changes** :  <we need to responsive it

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/125277258/1229efc6-fd82-4157-b9cf-1fbf402f3e01)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ramakrushna Biswal
- What is your participant role?  **GSSOC**

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@RamakrushnaBiswal website is updated already with responsiveness
