### ISSUE TITLE
Adding arrow button 

### ISSUE THREAD

**Issue by rashmi3149** [Avdhesh-Varshney/Chanakya-Niti#15]
description :-
Add arrow buttons to move to previous or next episode without the need to specifically search the episodes.

![Screenshot 2024-05-30 122951](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/113359160/b3016438-d0e5-4e05-b6ff-946d7a8dab44)

@Avdhesh-Varshney please assign this feature to me under SSOC'24.

**Comment by Avdhesh-Varshney** [comment]
@rashmi3149 Assigned to you.

**Comment by rashmi3149** [comment]
#20
