### ISSUE TITLE
🧑‍💻: Enhance Navigation bar.

### ISSUE THREAD

**Issue by aapJoysakoi** [Avdhesh-Varshney/chanakya-niti#150]
:red_circle: **Title** : Enhance Navigation bar
:red_circle: **Enhancement Aim** : improve the nav. bar. frontend
:red_circle: **Changes** : 
- make it's user interface more presentable and eye-catchy.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Joysa Kaushik
- Participant role : SSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aapJoysakoi** [comment]
please assign me under SSOC.

**Comment by Avdhesh-Varshney** [comment]
@aapJoysakoi go ahead.
