### ISSUE TITLE
🧑‍💻: Add favicon of chanakya in website

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/chanakya-niti#153]
:red_circle: **Title** : Favicon add
:red_circle: **Enhancement Aim** : make better view
:red_circle: **Changes** :  add link to favicon

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/126322584/d44eba25-d23c-4835-81e5-f17016216b7f)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhavy Zala
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Please assign me !

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy not required
