### ISSUE TITLE
🐛: hamburger icons needs to be closed icon if menu opens 

### ISSUE THREAD

**Issue by kapilG0** [Avdhesh-Varshney/chanakya-niti#154]
:red_circle: **Title** :
:red_circle: **Bug** :
:red_circle: **Changes** :  

### Screenshots 📷
![Screenshot_20240625_235809](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/59639410/117a0b94-4a25-4450-93a5-131c18c2db50)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by kapilG0** [comment]
Hello @Avdhesh-Varshney please assign this issue to me under gssoc 24

**Comment by Avdhesh-Varshney** [comment]
@kapilG0 it works as expected
