### ISSUE TITLE
🐛: In about page Image of chanakya is very big i will make it perfect.

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/chanakya-niti#156]
:red_circle: **Title** : Image size fix
:red_circle: **Bug** : Size of Image is very big
:red_circle: **Changes** :  Just add perfect height and width

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/126322584/af163214-e4a5-4087-8297-60ef6ef4c04c)

It is not visible fully in my laptop screen i will fix it.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhavy Zala
- What is your participant role? Gssoc'24
- 
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Please assign me this task !

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy go ahead.
I also thinks for adding more content in about section beutifully. If you can try and looks good, will increase the lavel of issue
