### ISSUE TITLE
🧑‍💻: Enhancement in Contributors 

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/chanakya-niti#158]
:red_circle: **Title** : Enhancement in Contributors 
:red_circle: **Enhancement Aim** : Remove Get details show details under cards
:red_circle: **Changes** : Some changes in Card

Under card show total Contributon and show github logo from click on that profile of that contributor opens in another tab.

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/126322584/c2034619-1e10-4842-8fdb-1ced2eb124bf)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhavy Zala
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Please check this we can remove contributor details and make our cards like this !

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy `Get Details` btn is required to show the contribution of each contributor on the website. If you want to work on the contributors card with glassmorphism effect?

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Ok I will do it !

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy go ahead.
