### ISSUE TITLE
Feature Request: Add Up/Down Arrow Buttons to Input Field.

### ISSUE THREAD

**Issue by AnkitLuhar** [Avdhesh-Varshney/Chanakya-Niti#16]
**Description:

Problem: Manually inputting numerical values is tedious and error-prone, hindering user experience.

Solution: Introduce up/down arrow buttons for effortless value adjustment, enhancing efficiency and reducing errors.

Benefits:

1> Improved user experience.

2> Reduced input errors.

3> Enhanced productivity.

4>Increased accessibility.

Labels: Feature Request, UX, Enhancement, gssoc 

Attachments:** 

![Screenshot (464)](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/142730608/f8de2eb2-1783-44cc-a365-edc69a766f0e)

**assign me  under gssoc24 .**

**Comment by AnkitLuhar** [comment]
This feature request is assigned under GSoc24. Awaiting your feedback to commence work promptly.

**Comment by Avdhesh-Varshney** [comment]
@AnkitLuhar Go ahead.

**Comment by AnkitLuhar** [comment]
hey,there is some issue i am facing right now,unable to resolve this issue ,here i am attaching issue that i facing during the compare and the pull request,and attachment::

![Screenshot (486)](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/142730608/8fc4527d-e6ef-4ae0-a7b5-dcfd984c7298)

**Comment by AnkitLuhar** [comment]
hey, @Avdhesh-Varshney , I've added increment and decrement buttons and synchronized them with episodes in real time. Could you please update the label and improve the issue's level, and add more labels according to your suggestion?

**Comment by Akash4701** [comment]
Please assign me for this feature update @Avdhesh-Varshney for SSoC'24

**Comment by AnkitLuhar** [comment]
@Akash4701 it is already been issued and completed

**Comment by Avdhesh-Varshney** [comment]
Not required!
