### ISSUE TITLE
🧑‍💻: Contributor detail page  

### ISSUE THREAD

**Issue by Madhavdua** [Avdhesh-Varshney/chanakya-niti#163]
**Contributor Details Page** :
Provide me requirements of details page for each contributor like it should contain no of contributions, their github etc.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Madhav Dua 
- SSOC contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Madhavdua i want to showcase the merged pr of the contributors along with no. of contributions and github link like a link tree structure. Are you able to do this and also attach the link of prs so that they will also go through the their merged prs.

**Comment by Madhavdua** [comment]
I am working on it. Will update you by tomorrow
