### ISSUE TITLE
🧑‍💻:  Adding tilt effect to the header image 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Avdhesh-Varshney/chanakya-niti#166]
:red_circle: **Title** : Adding titl effect to the header image 
:red_circle: **Enhancement Aim** : I want to add Tilting like effect when user hover on the image then the image looks like interacting with the user cursor 
:red_circle: **Changes** : Changes related to css

### Screenshots 📷

https://github.com/Avdhesh-Varshney/chanakya-niti/assets/118350936/2f546f93-2f75-4b8c-b9cb-c53d57aa48d2

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Ayushmaan Agarwal
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Ayushmaanagarwal1211 go ahead.
