### ISSUE TITLE
🧑‍💻:  Implementing Dark mode for the website

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Avdhesh-Varshney/chanakya-niti#167]
:red_circle: **Title** : Dark mode 
:red_circle: **Enhancement Aim** : Implementation of the dark mode which makes the website more attractive and increases the accessibility of the website 
:red_circle: **Changes** : Related to the html , js , jsx and css 

### Screenshots 📷
![Screenshot 2024-06-29 162110](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/118350936/de35aa66-9c56-46f8-b809-4d1c643700f7)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Ayushmaan Agarwal
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by MetiUmashri** [comment]
can you assign this to me

**Comment by MetiUmashri** [comment]
Under GSSOC

**Comment by Avdhesh-Varshney** [comment]
@MetiUmashri go ahead.

**Comment by Ayushmaanagarwal1211** [comment]
@Avdhesh-Varshney  Hlo this issue was raised by me please first assign in to me if i not able to do this then please assign it to @MetiUmashri

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney Hlo this issue was raised by me please first assign it to me give time for just today if i not able to do this then please assign it to @MetiUmashri

I've already written in guidelines, not raise more than 1 issue at a time.

**Comment by Ayushmaanagarwal1211** [comment]
@Avdhesh-Varshney srry sir i didn't read that but i will keep in mind and i am raising a pr for tilt effect after that can i work on that

**Comment by Ayushmaanagarwal1211** [comment]
@Avdhesh-Varshney  Sir i have raised the pr for that please check it and i am closing any other issue raised by me and please assign this to me

**Comment by MetiUmashri** [comment]
@Ayushmaanagarwal1211 you had labelled it up-for-grabs while raising this issue which means it is open for contributors, so didn't you pay attention to it.

**Comment by Ayushmaanagarwal1211** [comment]
Sir i didn't add any label to it

**Comment by Ayushmaanagarwal1211** [comment]
Sir i didn't is is auto applied maybe

**Comment by MetiUmashri** [comment]
You take this up @Ayushmaanagarwal1211

**Comment by MetiUmashri** [comment]
Ask for re-assign this issue to you

**Comment by Ayushmaanagarwal1211** [comment]
> Ask for re-assign this issue to you

Thank you so much for understanding 
@Avdhesh-Varshney  Please reassign

**Comment by Avdhesh-Varshney** [comment]
@Ayushmaanagarwal1211 go ahead.
