### ISSUE TITLE
🧑‍💻:  Adding Fade Up animations to the contributors cards

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Avdhesh-Varshney/chanakya-niti#168]
:red_circle: **Title** : Animation on cards 
:red_circle: **Enhancement Aim** : Adding a fade up animation which looks like coming up with some amazing effect
:red_circle: **Changes** : In css , jsx and js 

### Screenshots 📷

https://github.com/Avdhesh-Varshney/chanakya-niti/assets/118350936/918152db-895f-4318-ac3a-805581303b88

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Ayushmaan Agarwal
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
not required.
