### ISSUE TITLE
🧑‍💻: Add quiz in website

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/chanakya-niti#172]
:red_circle: **Title** : Add quiz 
:red_circle: **Enhancement Aim** : Add feature
:red_circle: **Changes** : Add quizes

### Screenshots 📷
It will show green in color if your answer is correct.
If answer wrong it shows red in that button and show correct answer.
I will add 10 quiz that will be from about chanakya page's details.
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/126322584/a09f54b8-8693-437c-b526-533138c4bf6f)
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/126322584/c044fb07-0c97-4410-b35c-103cc24bef26)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhavy Zala
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Please assign me this task !

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy This is a chanakya niti website. A spiritual/ historical website not a programming website?

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Picture is for demo for style i will add quations and answer about chanakya !

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy go ahead. But use any free api for it. Not any hard coded dataset.
