### ISSUE TITLE
🧑‍💻: Enhancement of the About Page

### ISSUE THREAD

**Issue by MetiUmashri** [Avdhesh-Varshney/chanakya-niti#174]
The UI of this page is basic so would like to enhance it with necessary css components.

### Screenshots 📷
<img width="944" alt="image" src="https://github.com/Avdhesh-Varshney/chanakya-niti/assets/97387069/5c44f74b-e892-4f39-b88f-abd8712157b9">

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Umashri 
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by MetiUmashri** [comment]
I have created this issue kindly assign it to me, @Avdhesh-Varshney By default here the label for up-for-grabs is added .

**Comment by Avdhesh-Varshney** [comment]
@MetiUmashri go ahead.
