### ISSUE TITLE
🧑‍💻:Add hover effects on home page cards 

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/chanakya-niti#177]
:red_circle: **Title** : Add hover effects
:red_circle: **Enhancement Aim** : Make attractive when hover
:red_circle: **Changes** : Add css for hover effects

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/126322584/db3f0231-a7c6-4e21-b6ed-11022f8b52eb)

![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/126322584/9fcfda52-6f56-4717-b55b-3c478fad5a87)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhavy Zala
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Please assign me this task !

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy go ahead.
