### ISSUE TITLE
🧑‍💻:  Theme Toggle Button , FAQs section

### ISSUE THREAD

**Issue by KajalBhatt123** [Avdhesh-Varshney/chanakya-niti#179]
:red_circle: **Title** :  Theme Toggle Button , FAQs section
:red_circle: **Enhancement Aim** : This issue aims to enhance the user experience of website by implementing a dark/light theme toggle button and adding a Frequently Asked Questions (FAQs) section.
:red_circle: **Changes** : 
Design a toggle button icon.
Adding a smooth transition effect when switching themes.
Adding a new section dedicated to Frequently Asked Questions.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Kajal Bhatt
- Participation role: GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by KajalBhatt123** [comment]
@Avdhesh-Varshney  kindly assign this to me and add GSSOC label

**Comment by Avdhesh-Varshney** [comment]
@KajalBhatt123 dark mode is implemented. Now, how this FAQs section helps user? And what will be the questions and answers?

**Comment by KajalBhatt123** [comment]
Adding a FAQs section will enhance the interactivity by allowing users to quickly find answers to common questions. questions could be like: Why should I use the Chanakya Niti website? What resources does it offer? Why is it necessary to know about Chanakya and his teachings? How does this help in personal growth and decision-making? @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
@KajalBhatt123 leave it, not required.
