### ISSUE TITLE
Episode No.

### ISSUE THREAD

**Issue by nishant0708** [Avdhesh-Varshney/chanakya-niti#18]
Instead of Adding Number manually 
![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/101548649/485e65a3-0bfb-438e-9d1d-347541576b62)
we can do it like 
Adding a episode list side bar which consist of Episode Number and title and

**Comment by Avdhesh-Varshney** [comment]
@nishant0708 can you elaborate your issue?
And join the discord server for further discussion.

**Comment by nishant0708** [comment]
See Currently User can enter episode number and listen that episode .but User don't know how many episodes are there and he can enter episode number which does not exist. instead getting episode number as an input we could make sidebar like this 
![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/101548649/bfa990ae-c927-41cc-a2d6-a74259ce85ad)
and display list of episodes. which will be convenient as well looks attractive.

**Comment by Avdhesh-Varshney** [comment]
@nishant0708 it is not looks nice. As i have keep the dataset on github which will fetch every audio and increase the download load of the user. It's not a good user experience. So, tell me any other approach or close it.

**Comment by nishant0708** [comment]
Uhmm getting it but the current problem is there is one input field to enter the episode number and user can enter any number .so if not sidebar  we can covert that input field to search bar and limit user to enter values given by us..

**Comment by Avdhesh-Varshney** [comment]
for discussion, join the discord server.
