### ISSUE TITLE
🧑‍💻:  Implement "Scroll to Top" Button

### ISSUE THREAD

**Issue by KajalBhatt123** [Avdhesh-Varshney/chanakya-niti#183]
:red_circle: **Title** : Implement "Scroll to Top" Button

:red_circle: **Enhancement Aim** :  I propose implementing a "Scroll to Top" button to enhance user experience by allowing users to easily navigate back to the top of the page.

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/133188585/9cdcd7fb-e47d-47e3-8f43-5fcf069ca135)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Kajal Bhatt
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@KajalBhatt123 go ahead.
