### ISSUE TITLE
🧑‍💻:  Audio section not in center and not stylish

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/chanakya-niti#185]
:red_circle: **Title** : Make Audio section stylish
:red_circle: **Enhancement Aim** : Better UI
:red_circle: **Changes** :  Position in center and add style.

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/126322584/89dc6b9e-a65f-408d-83a3-22d081466549)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhavy Zala
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Please assign me this task !

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy go ahead.
