### ISSUE TITLE
🧑‍💻:  Creating a login and signup page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Avdhesh-Varshney/chanakya-niti#186]
:red_circle: **Title** :  Creation of login signup page
:red_circle: **Enhancement Aim** : Creating the page for signup/login with email input , password and confirm password input
:red_circle: **Changes** :  Change in the login file to get it functional

### Screenshots 📷
![344386903-30d048dc-dcb7-41e4-8c6a-b7b31830e9f1](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/118350936/a588f18a-6f0a-46c3-a11a-8e1d9f4b0f35)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Ayushmaan Agarwal
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Ayushmaanagarwal1211 go ahead.

**Comment by Avdhesh-Varshney** [comment]
what's the update?

**Comment by Ayushmaanagarwal1211** [comment]
Yes yes I am creating actually I was busy with my exams I will make pr tomorrow
