### ISSUE TITLE
🧑‍💻: Fast Load up Chanakya image & make Home page and About page appealing in UI

### ISSUE THREAD

**Issue by shivamm-verma** [Avdhesh-Varshney/chanakya-niti#187]
:red_circle: **Title** : Fast Load up Chanakya image & make Home page and About page appealing in UI and 
:red_circle: **Enhancement Aim** : <i>Appealing UI</i>
:red_circle: **Changes** : 
- Download Chanakya image from source, to faster Load up! (in assets folder)
- Added Smooth transition from Light Mode to Dark Mode
- Changed Bg colors of cards in Home Page and added better hover & shadow effects in Dark Mode.
- Changed Bg color of About Chanakya card to some % of beige

### Home Page
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/dda96ba1-50da-4a87-bd0c-266f59829e70)
### About page
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/11177645-fe8f-4515-99ba-76f187940329)

### Home page
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/d231acf4-93e8-4663-8cac-5d4509a29de1)
### About page
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/de3e03b3-7ce0-4b15-8650-dc4e30b3cdc4)

# screen recordings
## before
https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/fbfc1e7f-c901-415e-a8ab-fc24d6fb1491

## after
https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/2281ecec-ede1-405b-aab7-658390a3302b

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shivam Verma
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by shivamm-verma** [comment]
Please @Avdhesh-Varshney 
Assign Me this Issue Under GSSOC, so that I can start working on it.

**Comment by Avdhesh-Varshney** [comment]
@shivamm-verma LGTM. But try to enhance, the ui using inline css only using bootstrap.

If possible, try to change the looks of website in light mode either changing colors and font.

**Comment by shivamm-verma** [comment]
Okay I am Opening a PR for this and Add changes to it.

**Comment by shivamm-verma** [comment]
New Changes in Light Mode

# New Changes (screenshots)
## before
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/84a6b0c4-a19f-4be9-a768-0f9de2f70ddd)
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/bd4ec200-cf52-4a19-981a-a9126cce3910)
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/bb9a44e0-46fb-44be-8aab-d5b8344c56db)


## After 
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/0259b485-69b7-4a4f-be87-2c5deb1bc9ad)
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/1d4ac0a6-6371-466f-8f9d-30758830ca31)
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/39c04dae-3f39-4fc3-855b-47f31f75c7ce)
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/c4e8e4fc-9a1d-46a7-9f7b-25154edd86fd)

## 

Please Check @Avdhesh-Varshney the New Deployments for this, In the mentioned PR.
