### ISSUE TITLE
🧑‍💻: Create the Signup page[frontend + backend]

### ISSUE THREAD

**Issue by arunimaChintu** [Avdhesh-Varshney/chanakya-niti#196]
:red_circle: **SignUp page** :
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** : 

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Arunima Dutta
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
gssoc
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UtkarshBirla28** [comment]
@arunimaChintu Sir assign me this issue i have worked on Signin/Signup page for many Repo's.
