### ISSUE TITLE
🧑‍💻:  Adding Footer 

### ISSUE THREAD

**Issue by dhairyagothi** [Avdhesh-Varshney/chanakya-niti#198]
:red_circle: **Title** :
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** : 

adding footer on website

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@dhairyagothi this issue is already present and mention your full name and participant role.
Raise the issue when no similar issue is present ok.
