### ISSUE TITLE
🧑‍💻: Design frontend of sing in and sing up form.

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/chanakya-niti#199]
:red_circle: **Title** : Singin and SingUp form
:red_circle: **Enhancement Aim** :  Security
:red_circle: **Changes** :  Add forms

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhavy Zala
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney assign it to me i will make PR under 24 hours.

As i see this issue has high priority but not solved till now so please assign it to me i will solve this as soon as possible.

**Thank You !**

**Comment by Shri6apr** [comment]
@Avdhesh-Varshney  
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/131538239/12047242-c14f-4707-a54e-48b1102c74a6)
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/131538239/1959cef4-a94f-445d-aa9a-0d1954395971)

**Comment by zalabhavy** [comment]
@Shri6apr you should follow the process.
This is not correct way to get issues.
