### ISSUE TITLE
 [UX Bug] Unable to Delete '1' in Input Bar for Episode Number

### ISSUE THREAD

**Issue by suryapratapsingh26** [Avdhesh-Varshney/Chanakya-Niti#2]
The input bar for the episode number restricts entry to numbers from 11 to 19, with the initial digit '1' being non-deletable. This limitation poses a usability issue, hindering user experience.

**Comment by suryapratapsingh26** [comment]
i am participant in gssoc'24 and i want to work on this issue so assign me this issue @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
@suryapratapsingh26 Assigned to you. For any discussion, join the discord server ok.
