### ISSUE TITLE
Add Docker Support for CHANAKYA-NITI 

### ISSUE THREAD

**Issue by nitishmalang** [Avdhesh-Varshney/chanakya-niti#200]
Adding Docker support to the CHANAKYA-NITI project for both the frontend and backend components. This will enable easier setup and deployment of the application.

Dockerfile for Frontend:

Sets up the React + Vite frontend in a Docker container.
Exposes port 3000.
 
Dockerfile for Backend:

Sets up the Node.js backend in a Docker container.
 Exposes port 5000.

  
docker-compose.yml:

Orchestrates the frontend and backend containers.
Simplifies the development and deployment process.

Could you please assign this issue to me under the SSOC 24 tag? I will implement Docker support for both the frontend and backend components and submit a pull request for review. Thank you!

**Comment by Avdhesh-Varshney** [comment]
@nitishmalang go ahead. If you need any credentials, mention me on discord server.

**Comment by nitishmalang** [comment]
> @nitishmalang go ahead. If you need any credentials, mention me on discord server.

sure
