### ISSUE TITLE
🧑‍💻: Add videos from youtube with API

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/chanakya-niti#204]
:red_circle: **Title** : Add Videos
:red_circle: **Enhancement Aim** : Feature
:red_circle: **Changes** :  Videos file

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhavy Zala
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney I will add youtube videos about chanakya with use of youtube api.
Please assign me !

**Thank You !**

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy go ahead.
