### ISSUE TITLE
🧑‍💻: Integrating Llama API to answer questions by users as if they are asked to Chanakya.

### ISSUE THREAD

**Issue by PranotiPD** [Avdhesh-Varshney/chanakya-niti#205]
:red_circle: **Title** : Integrating Llama api to answer questions as if they are asked to chanakya
:red_circle: **Enhancement Aim** : Just to give user experience of getting their questions answered by chanakya's way of thinking/principles
:red_circle: **Changes** :  We will need to add a page for interaction where users can ask questions that they have in mind and questions will be answered by Chanakya's way of thinking/principles. It will be fun/informative way to grab the user's attention. Let me know your thoughts.

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pranoti Durugkar
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@PranotiPD go ahead.

**Comment by PranotiPD** [comment]
Ok
