### ISSUE TITLE
Feat🧑‍💻: Adding star us, Visitors count in the footer

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Avdhesh-Varshney/chanakya-niti#209]
:red_circle: **Title** : Adding star us, Visitors count in the footer
:red_circle: **Enhancement Aim** : Star us button, visitor count
:red_circle: **Changes** : Creating element with styling

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/125277258/4b081d46-f429-4b5b-847f-238715b67428)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ramakrushna Biswal
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@RamakrushnaBiswal go ahead.
