### ISSUE TITLE
Feature Request: Add an option to change the speed of the audio

### ISSUE THREAD

**Issue by priyankeshh** [Avdhesh-Varshney/chanakya-niti#21]
I want to add an option for the user to switch between 1x 1.25x 1.5x 1.75x 2x while listening to the audio.

**Comment by priyankeshh** [comment]
@Avdhesh-Varshney  Can you please assign this to me under gssoc24

**Comment by Avdhesh-Varshney** [comment]
@priyankeshh go ahead.

**Comment by Sid-80** [comment]
@Avdhesh-Varshney I am willing to work on this issue under GSSOC24

**Comment by Avdhesh-Varshney** [comment]
@Sid-80 go ahead.
