### ISSUE TITLE
🧑‍💻:  Want to enhance the audio page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Avdhesh-Varshney/chanakya-niti#212]
:red_circle: **Title** : Enhance the audio page 
:red_circle: **Enhancement Aim** : Enhancing the audio page 
:red_circle: **Changes** :I want to give some colors ,custonizing for dark mode , want to give proper margin  

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/118350936/fed685e8-735d-4e6b-9669-5f79200e453d)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Ayushmaan Agarwal
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Ayushmaanagarwal1211 go ahead.
