### ISSUE TITLE
🧑‍💻: [Enhancement] : Want to add privacy notice and copyright policy 

### ISSUE THREAD

**Issue by Maana-Ajmera** [Avdhesh-Varshney/chanakya-niti#218]
:red_circle: **Copyright Policy and Privacy Notice** :
:red_circle: **I want to add seperate pages for privacy notice and copyright policy** :

### Screenshots 📷

NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Maana Ajmera
- What is your participant role? GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Maana-Ajmera** [comment]
@Avdhesh-Varshney I want to work on this issue , please assign it to me

**Comment by Avdhesh-Varshney** [comment]
not required.
