### ISSUE TITLE
🐛: [Bug] : Text not visible in dark mode in resources drop-down

### ISSUE THREAD

**Issue by Maana-Ajmera** [Avdhesh-Varshney/chanakya-niti#220]
:red_circle: **Text is not visible in dark mode in resources drop-down** :
:red_circle: **Bug** : Text is not visible in dark mode in resources drop-down
:red_circle: **Changes** :  I will turn the text background of resource dropdown to black and make its text white

### Screenshots 📷

https://github.com/Avdhesh-Varshney/chanakya-niti/assets/162733812/9e3f3538-a891-495a-b6e7-13c89e065855

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Maana Ajmera
- What is your participant role? GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Maana-Ajmera** [comment]
@Avdhesh-Varshney I want to work on this issue , please assign it to me

**Comment by Avdhesh-Varshney** [comment]
@Maana-Ajmera go ahead.
