### ISSUE TITLE
🧑‍💻:  Add Contribution.md file

### ISSUE THREAD

**Issue by chaanakyaaM** [Avdhesh-Varshney/chanakya-niti#222]
:red_circle: **Title** : Add contribution.md file
:red_circle: **Enhancement Aim** :  To add contribution.md file
:red_circle: **Changes** : 
Add contribution.md file.

I saw the contribution guidelines in the readme.md file, and I want to make a separate contribution.md file, this helps new contributors  for understanding the contribution guidelines easily without scrolling down the readme.md file for the contribution guidelines.

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Chaanakyaa Milkuri
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

**GSSOC**

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
not required.
