### ISSUE TITLE
🐛: hamburger icon needs to be replaced with close icon if menu opens 

### ISSUE THREAD

**Issue by kapilG0** [Avdhesh-Varshney/chanakya-niti#223]
:red_circle: **Title** :
:red_circle: **Bug** :
:red_circle: **Changes** :  

### Screenshots 📷
![Screenshot_20240711_000822](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/59639410/a51ca724-a1bf-41d4-b9af-1fae47ca62e6)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by kapilG0** [comment]
Hello @Avdhesh-Varshney please assign this issue to me under gssoc 24

**Comment by Avdhesh-Varshney** [comment]
@kapilG0 go ahead.
