### ISSUE TITLE
🧑‍💻: [Enhancement] : Adding favicon in website

### ISSUE THREAD

**Issue by Maana-Ajmera** [Avdhesh-Varshney/chanakya-niti#228]
:red_circle: **Title** : Adding favicon
:red_circle: **Enhancement Aim** : Making it look good to user
:red_circle: **Changes** : I want to add a favicon to the website

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/162733812/794a65d4-b8d1-485c-ae89-da4659a94b1a)

![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/162733812/e29d735a-0cf9-415d-a891-449f37595ea9)

We can add a chanakya icon as a favicon which will give a good look to our website , I think users will like this feature

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Maana Ajmera
- What is your participant role? GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Maana-Ajmera** [comment]
@Avdhesh-Varshney I want to work on this issue , please assign it to me

**Comment by Avdhesh-Varshney** [comment]
@Maana-Ajmera go ahead.

**Comment by TheNikhilRaj** [comment]
@Avdhesh-Varshney I want to work on this issue , please assign it to me!
