### ISSUE TITLE
🧑‍💻: add the book "Arthashastra" and "Chanakya Niti" in books section

### ISSUE THREAD

**Issue by ANKeshri** [Avdhesh-Varshney/chanakya-niti#229]
:red_circle: **Add book ARTHASHASTRA AND CHANAKYA NITI  ** :
:red_circle: **User will get to learn the book written by chanakya** :
:red_circle: **Addition of book** : 

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditya Narayan
- What is your participant role?  **GSSOC**

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ANKeshri** [comment]
@Avdhesh-Varshney please assign me this issue under gssoc labels .

**Comment by Avdhesh-Varshney** [comment]
@ANKeshri I'm not keeping any books pdf in the repo. I'm working on backend part to keep all the things in database and fetch from there.
