### ISSUE TITLE
🐛: Incorrect Chanakya Image Link in Audio Section

### ISSUE THREAD

**Issue by manasdeshpande** [Avdhesh-Varshney/chanakya-niti#236]
:red_circle: **Title** :Chanakya Image Link in Audio Section
:red_circle: **Bug** :Incorrect Image Link in Audio section
:red_circle: **Changes** :  re route the image link to the chanakya's image link

### Screenshots 📷
![image](https://github.com/user-attachments/assets/934286ef-a07a-4907-8eb5-1c089cb7814c)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Manas Deshpande
- What is your participant role?  GSSOC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
It's already solved.
