### ISSUE TITLE
[Bug] : Audio Time is invisible

### ISSUE THREAD

**Issue by DonaldReddy** [Avdhesh-Varshney/Chanakya-Niti#24]
When the audio is playing we cant see the audio remaining time and audio completed time.

@Avdhesh-Varshney please assign this issue to me under GSSOC.

**Comment by Avdhesh-Varshney** [comment]
@DonaldReddy i think audio time is visible. If you can either makes more clearer for user, go ahead.

**Comment by DonaldReddy** [comment]
@Avdhesh-Varshney I'll make it more visible for users.

**Comment by Nirvanjha2004** [comment]
@DonaldReddy  If you want any help....I can Help you..
