### ISSUE TITLE
🧑‍💻: Fix Audio Section and make it working

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/chanakya-niti#241]
:red_circle: **Title** : Audio Section 
:red_circle: **Enhancement Aim** : Audio Working
:red_circle: **Changes** : Add Code for Audio.

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhavy Zala
- What is your participant role?  Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Please assign me this task !

Thank You !

**Comment by Avdhesh-Varshney** [comment]
already working.
