### ISSUE TITLE
🧑‍💻: Add GitHub Desktop Contribution Instructions

### ISSUE THREAD

**Issue by PradnyaGaitonde** [Avdhesh-Varshney/chanakya-niti#244]
:red_circle: **Title** : Add GitHub Desktop Contribution Instructions
:red_circle: **Enhancement Aim** : 
:red_circle: **Changes** : 
I am interested in contributing to the project by adding detailed instructions on how to contribute using GitHub Desktop.

I believe that by providing clear and comprehensive guidance, we can encourage more contributors to participate in the project, especially those who prefer using GitHub Desktop for their contributions.

Could you please assign me the issue related to adding GitHub Desktop contribution instructions under gssoc24? I am excited about the opportunity to contribute to the project and help streamline the contribution process for others. 

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pradnya Gaitonde
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) GSSOC24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
not required.
