### ISSUE TITLE
Adding an Issue Template

### ISSUE THREAD

**Issue by Saumya-28** [Avdhesh-Varshney/Chanakya-Niti#26]
Creating an issue template for easy identification of the type of issue and organized contributions.

**Comment by Avdhesh-Varshney** [comment]
@Saumya-28 go ahead.

**Comment by Saumya-28** [comment]
Hi @Avdhesh-Varshney!
My open source program is gssoc

**Comment by Avdhesh-Varshney** [comment]
not required.
