### ISSUE TITLE
🧑‍💻: Addition of signup page

### ISSUE THREAD

**Issue by Sourabh782** [Avdhesh-Varshney/chanakya-niti#268]
:red_circle: **Title** :  SignUp page not working
:red_circle: **Enhancement Aim** : Additon of a signup page.
:red_circle: **Changes** : 
I wanted to add a SignUp page to the site

### Screenshots 📷

![Screenshot 2024-08-04 160629](https://github.com/user-attachments/assets/ab6211ed-6027-49a5-9178-ca17e3d1e820)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sourabh Singh Rawat
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC 2024
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by shubhamkumaar** [comment]
Anyone working on this?

Can you assign me?

**Comment by Avdhesh-Varshney** [comment]
Sorry this is under processing #279
