### ISSUE TITLE
Please allow me to improve styling of login page🧑‍💻: 

### ISSUE THREAD

**Issue by Its-your-rj** [Avdhesh-Varshney/chanakya-niti#269]
:red_circle: **Login page enhancement** :
:red_circle: **In order to make it more attractive to users** :
:red_circle: **I will try to make login page match with the background theme and will add few needed entries to it.**  

### Screenshots 📷
<img width="941" alt="image" src="https://github.com/user-attachments/assets/7bcdc0b5-f1c5-4d69-8678-f55756464c2d">

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Raj mehta
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Its-your-rj** [comment]
@Avdhesh-Varshney please assign me this taks under gssoc level it would be a great help to me

**Comment by itsaartii** [comment]
hey @Avdhesh-Varshney can you please assign me this issue. I would like to work on it.
