### ISSUE TITLE
Feature Update: Adding subtitles.

### ISSUE THREAD

**Issue by Saikat123Dev** [Avdhesh-Varshney/chanakya-niti#27]
I want to add subtitles for individual audio track. I want to work on this feature please assign me @Avdhesh-Varshney under ssoc24

**Comment by Avdhesh-Varshney** [comment]
@Saikat123Dev Assigned to you.

**Comment by Saikat123Dev** [comment]
@Avdhesh-Varshney  we can use some AI driven api or some chanakya-niti subtitle api to acomplish this feature .

**Comment by Avdhesh-Varshney** [comment]
@Saikat123Dev go ahead.

**Comment by Saikat123Dev** [comment]
@Avdhesh-Varshney Unfortunately i did not find any suitable or free AI api or some other alternative to acomplish this issue .

**Comment by Avdhesh-Varshney** [comment]
@Saikat123Dev join the project discord server as i will creating a meeting for this project movement discussion ok.
