### ISSUE TITLE
🐛: The resources dropdown button is not working in navbar.

### ISSUE THREAD

**Issue by nagalakshmi08** [Avdhesh-Varshney/chanakya-niti#270]
:red_circle: **Title** : Resources dropdown bug
:red_circle: **Bug** : The resources dropdown button is not working in navbar.
:red_circle: **Changes** :  Should add the dropdown option and give necessary options when resources button is clicked in navbar

### Screenshots 📷

https://github.com/user-attachments/assets/a62ba5a4-88e7-475e-8869-6da535e0297b

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Naga Kanaka Lakshmi
- What is your participant role? "My role is GSSOC'24 contributor"

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by rafiya2003** [comment]
please assign me this issue

**Comment by Avdhesh-Varshney** [comment]
It's now in working condition
