### ISSUE TITLE
Able to change main picture

### ISSUE THREAD

**Issue by Chelseasingla1** [Avdhesh-Varshney/chanakya-niti#28]
I would like to add feature of adding more pictures, or like giving next and back arrows to see multiple pics.
Please assign me this issue under SSOC.

**Comment by Avdhesh-Varshney** [comment]
@Chelseasingla1 go ahead.

**Comment by INam1995** [comment]
@Avdhesh-Varshney ,
I would like to add Carousel feature. Kindly assign me this issue under SSOC.
thank you!!

**Comment by Avdhesh-Varshney** [comment]
@Chelseasingla1 are you working on it?
