### ISSUE TITLE
🧑‍💻: Feature Request: Add AI Chatbot for Chanakya’s Teachings

### ISSUE THREAD

**Issue by Aryan0220** [Avdhesh-Varshney/chanakya-niti#280]
:red_circle: **Title** : Feature Request: Add AI Chatbot for Chanakya’s Teachings

:red_circle: **Changes** : I propose the addition of an AI-powered chatbot that will provide users with accessible, interactive content based on the teachings of Chanakya. The chatbot will allow users to ask questions and receive relevant insights from Chanakya’s work, promoting a deeper understanding of his philosophy.

Since, the platform focuses on delivering engaging content on the Chanakya, and the chatbot will enhance user interaction by allowing them to explore his teachings more dynamically.

***********************************************************************
- Full name : Aryan Bargal
- What is your participant role?  GSSOC

**Comment by Aryan0220** [comment]
Can use open source llm models for implementing the chatbot or can also use Openai API's for the same.

**Comment by Avdhesh-Varshney** [comment]
Open ai api is already implemented you can go through the website
https://chanakya-niti.vercel.app/resources/chanakyagpt

**Comment by Aryan0220** [comment]
> Open ai api is already implemented you can go through the website https://chanakya-niti.vercel.app/resources/chanakyagpt

Getting 404 error and unable to access resources from navbar.
Can I work to it ?

**Comment by Avdhesh-Varshney** [comment]
UI under processing. #278 #281
