### ISSUE TITLE
🧑‍💻: Add language translator

### ISSUE THREAD

**Issue by Aditijainnn** [Avdhesh-Varshney/chanakya-niti#283]
:red_circle: **Title** : Language translator
:red_circle: **Enhancement Aim** : To add language translator 
:red_circle: **Changes** :  It will translate the text to different language

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Aditi
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) gssoc ext and hacktiberfest
 
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Can you tell me the use case of this feature?

**Comment by Aditijainnn** [comment]
> Can you tell me the use case of this feature?

 language translator on this AI-driven digital platform enables users to access Chanakya's teachings in their preferred language.

**Comment by Avdhesh-Varshney** [comment]
Attach a working video in your pr to review it.

**Comment by Aditijainnn** [comment]
> Attach a working video in your pr to review it.

ok

**Comment by Avdhesh-Varshney** [comment]
#345
