### ISSUE TITLE
🧑‍💻: Enhance Navbar with Hover Effects and Animation

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [Avdhesh-Varshney/chanakya-niti#289]
:red_circle: **Title** :Enhance Navbar with Hover Effects and Animation
:red_circle: **Enhancement Aim** :Redesign the navbar to add engaging hover effects and animations for the logo and navigation items, improving user interactivity and overall visual appeal
 

### Screenshots 📷
 
![chanakya_navbar](https://github.com/user-attachments/assets/f3e055ef-4053-4b50-bc09-c30e209bb792)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Biswajit Sarkar
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.): gssoc ext and hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Utsav631** [comment]
I want to work on this issue. Assign me this.
