### ISSUE TITLE
Taking a note or mark in between audios

### ISSUE THREAD

**Issue by Chelseasingla1** [Avdhesh-Varshney/chanakya-niti#29]
I would like to add a feature where user can mark it or take a note in between where they stopped or if want to note something.
Please assign me this issue under SSOC.

**Comment by INam1995** [comment]
Dear @Avdhesh-Varshney ,
I propose adding a feature that allows users to mark their progress or take notes. Please assign this issue to me under SSOC.
Thank you.

**Comment by Avdhesh-Varshney** [comment]
@INam1995 go ahead.

**Comment by Chelseasingla1** [comment]
> @INam1995 go ahead.

hi i was the one who raised this issue?

**Comment by Avdhesh-Varshney** [comment]
> > @INam1995 go ahead.
> 
> hi i was the one who raised this issue?

But 1 issue is already assigned to you. I have already told for raising 1 issue at a time.
