### ISSUE TITLE
set up backend and add a api to receive mail of the user

### ISSUE THREAD

**Issue by AyushSharma72** [Avdhesh-Varshney/chanakya-niti#290]
:red_circle: **Title** : add a contact us page
:red_circle: **Enhancement Aim** : to create a contact us page and form

### Screenshots 📷
 N/A 

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ayush Sharma
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
- 
 @gssoc-ext

please assign this issue to me @Avdhesh-Varshney 
I have also contributed in many repos in gssoc-ext with the same issue
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Utsav631** [comment]
I am confident, I can do this easily. Assign mw this issue.

**Comment by Avdhesh-Varshney** [comment]
Not required.
