### ISSUE TITLE
🧑‍💻: SCROLL BACK BUTTON FOR THE ABOUT SECTION✨

### ISSUE THREAD

**Issue by shriyadindi** [Avdhesh-Varshney/chanakya-niti#297]
:red_circle: **Title** : I would like to add a scroll back button for the about section
:red_circle: **Enhancement Aim** :Scroll back button

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shriya Dindi
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC, Hacktoberfest
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
#294
