### ISSUE TITLE
🧑‍💻: add language translator

### ISSUE THREAD

**Issue by ananyag309** [Avdhesh-Varshney/chanakya-niti#306]
:red_circle: **Title** :add language translator
:red_circle: **Enhancement Aim** : "Implement a language translator to support Indian native languages. This feature will allow users to translate content into languages such as Hindi, Tamil, Telugu, Bengali, and others, enhancing accessibility and user experience."
:red_circle: **Changes** :  use google api

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ananya Gupta
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) gssoc ext hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
#283
