### ISSUE TITLE
🧑‍💻: add faq modal at footer

### ISSUE THREAD

**Issue by ananyag309** [Avdhesh-Varshney/chanakya-niti#307]
:red_circle: **Title** : add faq modal at footer
:red_circle: **Enhancement Aim** : "Add an FAQ modal to the footer section of the website to provide users with quick access to common questions and answers. This feature will improve user experience by offering immediate support and information."
:red_circle: **Changes** :  popup modal at footer

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  ananya gupta
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) gssoc ext hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
#287
