### ISSUE TITLE
Information button

### ISSUE THREAD

**Issue by Chinmayeep58** [Avdhesh-Varshney/Chanakya-Niti#31]
Hovering on this information button would provide the user with the main purpose of this website.

It will look like this
![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/146485755/cd9e8399-b461-4582-a572-ba7a12998452)
![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/146485755/cd162d38-4c99-437c-a1ff-c7a70da26fe2)

Please assign this issue to me.

**Comment by Avdhesh-Varshney** [comment]
@Chinmayeep58 go ahead.

**Comment by Chinmayeep58** [comment]
I have applied through SSOC'24
