### ISSUE TITLE
🧑‍💻: Updating twitter icon to X

### ISSUE THREAD

**Issue by tanishirai** [Avdhesh-Varshney/chanakya-niti#319]
:red_circle: **Title** : Updating twitter icon to X in Login page
:red_circle: **Enhancement Aim** : Enhancing brand consistency
:red_circle: **Changes** : Changing bird twitter icon to X icon

### Screenshots 📷
Before
![image](https://github.com/user-attachments/assets/e40a3a10-e688-4cfb-b272-0ae60f16e8e2)

After
![Screenshot 2024-10-21 001638](https://github.com/user-attachments/assets/389e6e4c-0263-4f0a-92a8-5bd4267d0ccb)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Tanishi Rai
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
    GSSoC'24-Extd, Hacktoberfest
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by cypher4802** [comment]
Name: Tanmay Sharma
For HacktoberFest
@saras-69 Hello I want to contribute can U please assign me the issue and add label of hacktoberfest
