### ISSUE TITLE
Adding mulimedia button to change the episode

### ISSUE THREAD

**Issue by ansh7432** [Avdhesh-Varshney/Chanakya-Niti#32]
![Screenshot from 2024-06-01 21-23-34](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/131197259/76a2ec7e-0d6e-4b0d-bc6e-710f752e7eef)

Adding an button to change to the next or previous episode through the player only 
Please assign me this issue under ssoc'23

**Comment by Avdhesh-Varshney** [comment]
@ansh7432 already done.
