### ISSUE TITLE
🧑‍💻: Documentation: Wanted To Add Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [Avdhesh-Varshney/chanakya-niti#323]
:red_circle: **Title** : Adding Of Contributing.md
:red_circle: **Enhancement Aim** : I wanted to add the contributing.md file which will help the contributors to easily contribute. It will also help them understand the correct way of following coding practices and other important things.
:red_circle: **Changes** : 

Wanted to do the following changes :-

1) Enhance the project structure
2) Add need help with the basics section
3) Add project structure section
4) Add additional method of contributing through GitHub desktop section
5) Add good coding practices section
6) Add the help and support section
7) Add the pull request section
8) Add issue report process section

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : MILAN P SAMUEL
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC Extend

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Not required.
