### ISSUE TITLE
Enhancement in home page for episode selection

### ISSUE THREAD

**Issue by Unnati101** [Avdhesh-Varshney/Chanakya-Niti#33]
I want to add separate button like drop down to select episode instead of entering the episode no as it is not that how many episodes are there.  Also the overall interface can be made a lot better by adding some back ground. 

assign this issue to me and I will make the necessary changes.
kindly add the gssoc tag as well

**Comment by Avdhesh-Varshney** [comment]
@Unnati101 can you explain how this is beneficial for a good user experience?
Explain it by visualizing.

**Comment by khushi25916** [comment]
hey, I feel like it will be helpful to add navigation bar for user to track their progress, if u like it pls assign it to me it's no:- 61

**Comment by Avdhesh-Varshney** [comment]
@Unnati101 @khushi25916 join the project discord server, i am creating a meeting tomorrow. Discuss it there.

**Comment by khushi25916** [comment]
> @Unnati101 @khushi25916 join the project discord server, i am creating a meeting tomorrow. Discuss it there.

ok

**Comment by Avdhesh-Varshney** [comment]
@Unnati101 go ahead.
