### ISSUE TITLE
🧑‍💻:  Adding feedback form

### ISSUE THREAD

**Issue by TBorundia** [Avdhesh-Varshney/chanakya-niti#336]
:red_circle: **Title** : Adding feedback form
:red_circle: **Changes** : Create a feedback form to collect user input and improve website features. The form should include the following:

Input fields for name, email, and feedback message.
A star rating system for user satisfaction.
Form validation to ensure all fields are correctly filled before submission.
A responsive design that works seamlessly on all devices.
A success/failure message after form submission.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by cypher4802** [comment]
@TBorundia I am keen to work on the issue can u pls assign me
Name: Tanmay Sharma
For Hacktoberfest(Pls add label)

**Comment by TBorundia** [comment]
@Avdhesh-Varshney  , Please assign this issue to me .
