### ISSUE TITLE
 Daily Chanakya Wisdom: Inspire and Engage Every Day

### ISSUE THREAD

**Issue by Akash4701** [Avdhesh-Varshney/Chanakya-Niti#34]
1.Feature Description:

Share a daily quote or insight from Chanakya's teachings to keep users motivated, engaged, and regularly interacting with the platform. This feature will provide a constant touchpoint for users, encouraging them to visit the site daily for new wisdom.

2.Solution:

>Register on the API provider’s website and obtain the necessary API keys.
>Compile a collection of approximately 200 Chanakya quotes and store them in your own database.
>Daily Fetch Logic: Set up a scheduled task to fetch a daily quote from the chosen API.
Filter by Author: In the API request, attempt to filter quotes by the author "Chanakya."
Fallback Mechanism: If the API does not return a Chanakya quote, retrieve a quote from your internal database instead.
> Mind Freshening Motivation Section:  A dedicated section on your homepage  within your application for the daily quote.
Styling: Use Tailwind CSS to style the quote section, ensuring it is visually appealing and aligns with your overall design.
>Regular Updates: Periodically update your internal database with new Chanakya quotes to keep content fresh.

3.Advantages:

Regular Interaction: Daily quotes encourage users to return to the app regularly, increasing engagement.
Inspiration and Motivation: Chanakya's teachings can provide daily inspiration, making users feel connected and motivated.
Content Freshness:

Variety: A rotating selection of quotes keeps content fresh and interesting.
Relevance: Users can start their day with new insights, enhancing the perceived value of the app.

**Comment by Akash4701** [comment]
Please assign me for this feature update @Avdhesh-Varshney  for ssoc24

**Comment by Avdhesh-Varshney** [comment]
@Akash4701 go ahead.
