### ISSUE TITLE
After playing video timing not showing properly 

### ISSUE THREAD

**Issue by kapilG0** [Avdhesh-Varshney/Chanakya-Niti#35]
![Screenshot_20240602_162219](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/59639410/71d3c086-6105-4f79-861a-967603e25770)

**Comment by kapilG0** [comment]
Hello @Avdhesh-Varshney please assign this issue to me under gssoc 24

**Comment by Avdhesh-Varshney** [comment]
@kapilG0 already issue is present #24
