### ISSUE TITLE
🧑‍💻: Adding back button on quiz pages and after the quiz submission.

### ISSUE THREAD

**Issue by VinayLodhi1712** [Avdhesh-Varshney/chanakya-niti#351]
:red_circle: ** Adding back button on quiz pages and after the quiz submission.* :
:red_circle: **There would be a back-button** :
:red_circle: **Changes** : 1. back button on quiz page to go to the back

### Screenshots 📷
![backbutton2](https://github.com/user-attachments/assets/87d0a0ac-d6de-476e-b60a-ab73b59afc45)

There is no good User experience if there is no back button on the pages it will lead user to use chrome default back button or using logo to go home page it is not good thing for user.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Vinay Anand Lodhi
- What is your participant role? GSSoC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by AADESHak007** [comment]
Hey @VinayLodhi1712 I want to work upon this issue . I am contributor under GSSOC-extd and HACKTOBERFEST

**Comment by rafiya2003** [comment]
kindly assign me this issue
