### ISSUE TITLE
🐛: The oauth buttons in login page doesn't work | Adding oauth in all the pages

### ISSUE THREAD

**Issue by Edasgh** [Avdhesh-Varshney/chanakya-niti#352]
Buttons are there in ui but implementation is not yet done i would like to work on this issue. I want to implement oAuth like google, facebook, twitter and github
Please assign this issue to me under gssoc-ext, hacktoberfest-accepted and a relevant level labels

### Screenshots 📷
![Screenshot 2024-10-24 202027](https://github.com/user-attachments/assets/5e24cfa7-a9e6-4118-9a0e-ac3aad1ff873)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Eshita Das
- What is your participant role? GSSOC

**Comment by Avdhesh-Varshney** [comment]
If you need any help, communicate through discord

**Comment by Edasgh** [comment]
> If you need any help, communicate through discord

Ok

**Comment by Edasgh** [comment]
@Avdhesh-Varshney please check my PR
