### ISSUE TITLE
🧑‍💻: Menu button and and nav menu

### ISSUE THREAD

**Issue by Hemraj-7** [Avdhesh-Varshney/chanakya-niti#355]
:red_circle: **Title** : Menu button and and nav menu
:red_circle: **Enhancement Aim** : for website looking good
:red_circle: **Changes** : when we click on the menu button in small devices like mobile phone then the menu button show but they are don't have background that is looking bad and mix with website contents. so i want to add background in the menu

### Screenshots 📷
![Screenshot 2024-10-25 134932](https://github.com/user-attachments/assets/51906b15-25ba-419e-b92c-f78157faad16)

![Screenshot 2024-10-25 135008](https://github.com/user-attachments/assets/0cb805bf-cf7a-4556-9e7c-ec7d82d88300)

all the menu like- 
about
login
contributor etc. mix with the website content

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Hem Raj
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.): GSSOC-Ext24

***********************************************************************

**Comment by DINES-04** [comment]
i find the issue of  overflow the component of navigation  bar :
![image](https://github.com/user-attachments/assets/0572acfc-a796-4fbc-94b3-506a31dad0a6)
 
and i wish to change the issue to impove the project

@Hemraj-7 Could you please assign this home page design enhancement task to me and label it for contribution? I’m excited to start working on it. Thank you!

full name: DINES
Github: DINES-04
participant role: GSSOC | Contributor

**Comment by DINES-04** [comment]
@sanjay-kv could you help mentor is not replay
