### ISSUE TITLE
After starting app margin needs to be done between header message and content 

### ISSUE THREAD

**Issue by kapilG0** [Avdhesh-Varshney/Chanakya-Niti#36]
![Screenshot_20240602_162412](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/59639410/46adc594-121f-4c86-bef0-15808609e7c1)

**Comment by kapilG0** [comment]
Hello @Avdhesh-Varshney please assign this issue to me under ssoc 24

**Comment by Avdhesh-Varshney** [comment]
@kapilG0 go ahead.

**Comment by kapilG0** [comment]
Hello @Avdhesh-Varshney i have raised pr #99 for this issue . can you label from ssoc to gssoc if posible please . Thanks
