### ISSUE TITLE
🐛:  ChanakyaGPT || Not Responding 

### ISSUE THREAD

**Issue by Nkovaturient** [Avdhesh-Varshney/chanakya-niti#360]
:red_circle: **Title** : ChanakyaGPT Feature Improvement
:red_circle: **Bug** : Not responding to user's input and returning console errors
:red_circle: **Changes** :  I would like to enhance and overhaul the GPT fetching data from groq-sdk

- Handling the  user Input
- Ensuring the GPT auth, activation, and  func works well so that the response and messages are desirably fetched and rendered responsibly.

### Screenshots 📷

![chanakyaNitiIssue](https://github.com/user-attachments/assets/91fe4017-4ee2-453d-a14e-1e4aee51fb6c)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Neha Kumari
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
- GSSOC Extd'24 || Contributor (Hactoberfest)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
I think api key is expired

**Comment by Nkovaturient** [comment]
> I think api key is expired

Alright! 
Will see. 
Thanks for assigning!

**Comment by Nkovaturient** [comment]
Hello @Avdhesh-Varshney ,
I have successfully implemented a robust ChanakyaGPT  and created a PR. Kindly look into it and guide me further.
