### ISSUE TITLE
🧑‍💻: Build Discussion Forums and Community Features

### ISSUE THREAD

**Issue by Anshikapal05** [Avdhesh-Varshney/chanakya-niti#366]
:red_circle: **Title** :Build Discussion Forums and Community Features
:red_circle: **Enhancement Aim** :Allow users to discuss, ask questions, and share their interpretations of Chanakya's teachings.
:red_circle: **Changes** : 
Add Discussion Forums and Community Features

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anshika Pal
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Anshikapal05** [comment]
@Avdhesh-Varshney kindly assign this issue to me.it would be really kind of you!
thank you!

**Comment by Avdhesh-Varshney** [comment]
How can you resolve this issue?

**Comment by Anshikapal05** [comment]
It is just an enhancement that I will add to site. There will be one section of discussion forum where people can share their teachings and learnings. Others can view it and can get inspired. It will be like a community for all like minded peoples.
