### ISSUE TITLE
Adding an error page 

### ISSUE THREAD

**Issue by Sumkaur02** [Avdhesh-Varshney/Chanakya-Niti#37]
Error page is not defined in this website currently . I can make Error Page and can give option to redirect to the Home Page 
Current Scenario
![Screenshot 2024-06-02 162512](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/144603204/b34f7c7a-aeef-483a-81c3-16024f21de14)
Expected result 
![Screenshot 2024-06-02 153718](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/144603204/27c78f71-78e8-4dbb-9587-00eeb526d316)

**Comment by Avdhesh-Varshney** [comment]
@Sumkaur02 currently this project is not contains so many pages. So, No need of it.
