### ISSUE TITLE
🧑‍💻: improve the feedback form user interface

### ISSUE THREAD

**Issue by Vivisteria11** [Avdhesh-Varshney/chanakya-niti#377]
**Title** :
:red_circle: **Enhancement Aim** :
:red_circle: I want to create more fields in the feedback form so that the responses are more niche which can be used to further improve the website

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Rakshita V 
- GSSOC extended contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UjjawalPrabhat** [comment]
Hi! I’d like to work on this issue. Could you please assign it to me? Thanks!
