### ISSUE TITLE
On playing of audio, it's difficult to see time stamps due to dark colored text used

### ISSUE THREAD

**Issue by rajRishi22** [Avdhesh-Varshney/Chanakya-Niti#38]
![Screenshot 2024-06-02 180243](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/98014028/f908cbcf-d74c-4d81-82c0-3a393e247339)
I want to fix this issue and even add slidebar to show time currently pointed by it.

**Comment by Avdhesh-Varshney** [comment]
@rajRishi22 already work going on #24
