### ISSUE TITLE
# Feature Request: Speed-Up Function (1.5x, 2x Playback Speeds)

### ISSUE THREAD

**Issue by Atanu789** [Avdhesh-Varshney/Chanakya-Niti#39]
**Describe the feature**
Adding speed-up buttons (1.5x, 2x) for playback would enhance user experience by allowing users to consume content more quickly according to their preference.

**Expected behavior**
Users should be able to control playback speed with options such as 1.5x and 2x, providing more flexibility in how they use the application.

**Additional context**
Many users find speed control features beneficial, especially for educational or informational content, as it allows them to adjust the pace according to their needs.

**Comment by Atanu789** [comment]
hey @Avdhesh-Varshney 
please assign me this issue

**Comment by Avdhesh-Varshney** [comment]
@Atanu789 issue already present #21
