### ISSUE TITLE
# Feature Request: Enhance Background and Player Card Interactivity

### ISSUE THREAD

**Issue by Atanu789** [Avdhesh-Varshney/Chanakya-Niti#41]
**Describe the feature**
The application currently lacks a background, and the player card is not very interactive. Adding a visually appealing background and enhancing the player card with CSS would improve the overall user experience.

**Expected behavior**
- A visually appealing background should be added to the application.
- The player card should be made more interactive with CSS enhancements, such as hover effects, shadows, and animations.

**Additional context**
Enhancing the UI with a background and interactive player card can make the application more engaging and user-friendly.

**Comment by Atanu789** [comment]
hey @Avdhesh-Varshney 
please assign this issue to me

**Comment by Avdhesh-Varshney** [comment]
@Atanu789 mention your open source program.

**Comment by Atanu789** [comment]
I will add a animated wave type of background which will enhance the user experience
and for the music player card i will also add animation and hover effects.
kindly assign me the issue.

**Comment by Avdhesh-Varshney** [comment]
@Atanu789 go ahead.
