### ISSUE TITLE
User registration and login infos

### ISSUE THREAD

**Issue by captainsahil001** [Avdhesh-Varshney/Chanakya-Niti#42]
User registration to the site their datas and user login while using the site

**Comment by Avdhesh-Varshney** [comment]
@captainsahil001 elaborate it more and mention your open source program.
For further discussion purpose, join the discord server.

**Comment by captainsahil001** [comment]
actually i was saying to integrate the user profile system where user can get to know their datas of which episode they are watching and have watched by making a user registration system through gmail login or any other in the database

**Comment by Avdhesh-Varshney** [comment]
@captainsahil001 join project discord for further discussion.

**Comment by Avdhesh-Varshney** [comment]
@captainsahil001 issue already assigned #25
