### ISSUE TITLE
#Feature Request Saving Listened Episode History

### ISSUE THREAD

**Issue by ansh7432** [Avdhesh-Varshney/chanakya-niti#43]
I would like to implement a feature to save user listened episodes and provide the ability for users to mark episodes for re-listening. This feature will include the creation of user registration and login functionality to save and manage their data effectively

**Episode History Tracking:**

_Listening History:_

Track episodes that the user has listened to.
Save the listening history in the database associated with the user.

_Mark for Re-listening:_

Allow users to mark episodes they want to listen to again.
Update the user’s episode history with the marked episodes.

_Registration Page:_
Form to collect username, email, and password.
Backend API to handle user registration and save data to the database.

_Login Page:_
Form to collect email and password.
Backend API to handle user login and authenticate users.

**Comment by ansh7432** [comment]
Please assign me this issue @Avdhesh-Varshney under SSoC'24

**Comment by Avdhesh-Varshney** [comment]
@ansh7432 go ahead

**Comment by ansh7432** [comment]
Hii @Avdhesh-Varshney Is it okay if I use Node.js with Express and MongoDB instead of Python Django for the project?

**Comment by Avdhesh-Varshney** [comment]
@ansh7432 join project discord for discussion purpose.
