### ISSUE TITLE
Issue: Track don't stop on invalid episodes

### ISSUE THREAD

**Issue by Madhavdua** [Avdhesh-Varshney/chanakya-niti#44]
when i enter a number, on which no episode can be found, then last playable tracks keeps playing.
It keeps playing that track untill, any other valid track is played.
For better understanding, i have provided a screenshot in which it has error loading 1000 episode, but it is still playing last valid episode(no. 1).
![Screenshot 2024-06-02 202458](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/94641232/74e81b47-b05e-42bb-ae1e-9253c50bef3d)

**Comment by Avdhesh-Varshney** [comment]
@Madhavdua go ahead.

**Comment by Madhavdua** [comment]
Thanks for assigning this issue to me! I'm excited to get started as this project aligns with my goals as an **SSOC** participant.
