### ISSUE TITLE
Bug : Audio Timestamp not visible clearly

### ISSUE THREAD

**Issue by ansh-h-mehta** [Avdhesh-Varshney/Chanakya-Niti#48]
The Audio timestamp is very difficult to see due to the font color used. A lighter color would help the user to navigate through the audio easily.

![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/99081110/a8be9f01-b66a-4e6c-bec8-646e570d21c7)

**Comment by ansh-h-mehta** [comment]
Please assign this issue to me under GSSOC'24. I'd be happy to fix it.

**Comment by DonaldReddy** [comment]
#24

**Comment by Avdhesh-Varshney** [comment]
@ansh-h-mehta it's done.
