### ISSUE TITLE
Change the css for previous next button from issue #15

### ISSUE THREAD

**Issue by priyankeshh** [Avdhesh-Varshney/Chanakya-Niti#50]
![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/102135464/8b83945b-741d-4571-a5d4-72488082b7da)

The Previous and Next button appear like this
I want to change it so that it looks the same as rest of the card:

![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/102135464/93cd0fdb-d1d0-450b-a3ff-666db68cdb85)

**Comment by priyankeshh** [comment]
@Avdhesh-Varshney Can you please put this under GSSoC 24

**Comment by phoenix020903** [comment]
Can I work on this issue?

**Comment by priyankeshh** [comment]
> Can I work on this issue?

check PR #51

**Comment by Avdhesh-Varshney** [comment]
Not required!
