### ISSUE TITLE
[Feature] Add 'Up Next' card to show next Audio Episode

### ISSUE THREAD

**Issue by ShreeluSantosh** [Avdhesh-Varshney/Chanakya-Niti#53]
**Why this feature proposal**
From the repo code, it's clear that there is a total of 806 audio episodes. While playing the episodes, the user has no idea how many episodes are left. 

This causes the user to keep playing the episodes until they reach the last episode, thinking that there will be more episodes up next.

**Steps**
I propose to add a card next to the episode play card so that the user can easily view the episode number and title of the next episode.

**Screenshots**
These are the screenshots from my draft on how the Up Next feature would look like.

1. On any of episodes 1-805
![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/94289402/6c5bf99e-784c-4762-bc23-2e8fb18c540f)

2. On episode 806
![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/94289402/1d06dae0-5369-4fce-b513-b8ca6ab5e418)

**Program**
SSOC

**Comment by Avdhesh-Varshney** [comment]
@ShreeluSantosh this will not worked well. As whole data of chanakya niti is kept on github which will fetch all the contents. So, this will not a good choice.
Is there anything else are you thinking?

For further discussion purpose, join the project discord server.

**Comment by Avdhesh-Varshney** [comment]
@ShreeluSantosh go ahead.
