### ISSUE TITLE
Adding the total number of episodes present.

### ISSUE THREAD

**Issue by AnantAgarwaL11** [Avdhesh-Varshney/Chanakya-Niti#56]
Adding the total number of episodes which are present after inputting the episode number so that user will not face any trouble . If the user enters 899 he does not know that till which episode the data is 
![Screenshot 2024-06-03 141219](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/115874061/5f67c096-b5b0-4bb4-b96a-de1efe0ddb5c)

**Comment by Avdhesh-Varshney** [comment]
@AnantAgarwaL11 already assigned #44
