### ISSUE TITLE
Improvements: [SSOC-24]

### ISSUE THREAD

**Issue by Madhavdua** [Avdhesh-Varshney/chanakya-niti#58]
1. Play episode 1 by default
2. Improve UI. To get some idea about improved UI, i have provided a Screenshot (not final).
 Kindly assign me this task to work on CSS.
![Screenshot 2024-06-03 150052](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/94641232/83dac8cb-e610-48db-8340-c5b05c7f94b1)

**Comment by Avdhesh-Varshney** [comment]
@Madhavdua go ahead.
