### ISSUE TITLE
Adding Footer to the website

### ISSUE THREAD

**Issue by narayani9120** [Avdhesh-Varshney/chanakya-niti#60]
## Description

Adding footer to the website such that the footer it contains the social media links so that the user can contact and if they wish to add a episode they can add with the help of admins. The work of adding episodes can be simplified for that the footer section would be very helpful.

Current Screenshot
![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/125353066/91752d3d-87b3-4470-a698-11d98cdf9b33)

Expected
![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/125353066/87c58c59-0b5d-40a0-9213-71d9c9e48cf8)

I am GSSoC'24 Contributor

Kindly assign me this issue @Avdhesh-Varshney

**Comment by Mallik0** [comment]
Hi there!
I just noticed that there isn't any footer section in the website, the foooter section plays a major role as it lets the users interact with us regarding any kind of queries, therefore i feel i can work on this issue easily so kindly assign this issue to me @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
@narayani9120 go ahead.

**Comment by INam1995** [comment]
Hi @Avdhesh-Varshney,
I propose adding a footer to the website that includes social media links, making it easier for users to contact us. Additionally, this footer will streamline the process for users to submit episodes with the help of admins.
I am a GSSOC'24 contributor
Thank you,

**Comment by Avdhesh-Varshney** [comment]
@narayani9120 solve it within 1 day.

**Comment by RamakrushnaBiswal** [comment]
hi @Avdhesh-Varshney can i work upon it

**Comment by Avdhesh-Varshney** [comment]
> hi @Avdhesh-Varshney can i work upon it

go ahead

**Comment by ROKUMATE** [comment]
@Avdhesh-Varshney If the Footer Issue is also not been solved I would like to work on this issue ... 
I will Try to give the pull request by the end of the day if u assign mee today 

Can You give me all the handles links so that I can make that footer responsive as well ?

I am A GSSOC Contributer

**Comment by komal-agarwal5** [comment]
@Avdhesh-Varshney I can design a footer with name of site,links, and chanakya image on left hand side.I am a GSSOC contributor.Can you please assign it to me?I will surely complete it within a single day

**Comment by shivamm-verma** [comment]
I Would Like to work on this Issue @Avdhesh-Varshney 

# Screenshots
## before
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/e0f49def-4a21-42c1-92f7-f1a271047113)

## After
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/bcae6366-c05b-41ed-a0ed-3f68778815e1)
![image](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/42126d1c-dd4b-4c9f-b130-f4b0ed68cfdb)

## After (screenRecording)
https://github.com/Avdhesh-Varshney/chanakya-niti/assets/98605616/6383eca7-984d-4a0c-ade9-ec4211ad649f

#

Please Assign Me this Issue @Avdhesh-Varshney
