### ISSUE TITLE
Feature Request: Add a Quiz on Chanakyaniti Principles

### ISSUE THREAD

**Issue by Satyam3002** [Avdhesh-Varshney/chanakya-niti#62]
Could we add a quiz about Chanakyaniti to help users test what they've learned? I think it would make our site more engaging.

**Comment by Avdhesh-Varshney** [comment]
@Satyam3002 good idea. go ahead.

**Comment by Satyam3002** [comment]
thanks

**Comment by Avdhesh-Varshney** [comment]
@Satyam3002 are you working on it?

**Comment by PDBharadwaj** [comment]
@Avdhesh-Varshney I want to work on this issue. Please assign me under GSSOC'24.

**Comment by Avdhesh-Varshney** [comment]
@PDBharadwaj go ahead. You need to remove last created quiz section, create a interactive ui for it and add good questions.

**Comment by PDBharadwaj** [comment]
> @PDBharadwaj go ahead. You need to remove last created quiz section, create a interactive ui for it and add good questions.

Okay @Avdhesh-Varshney
