### ISSUE TITLE
[FEAT] Next Episode Button

### ISSUE THREAD

**Issue by Atanu789** [Avdhesh-Varshney/Chanakya-Niti#66]
**Feature Description**
Implement a "Next Episode" feature to enable seamless transition to the next episode after finishing one, enhancing user engagement and experience.

**Functionality**
1. Detect completion of an episode.
2. Display a "Next Episode" prompt or button.
3. Automatically load and play the next episode upon user selection.

**Expected Benefits**
1. Improved User Experience.
2. Increased Engagement.
3. Time-saving.

**Comment by Atanu789** [comment]
hey @Avdhesh-Varshney kindly assign me this issue under #ssoc24

**Comment by Avdhesh-Varshney** [comment]
@Atanu789 follow the instruction provided on discord server.

**Comment by Avdhesh-Varshney** [comment]
@Atanu789 leave it. Not required and planned.
