### ISSUE TITLE
[FEAT] Adding cookies to save the progress of the user

### ISSUE THREAD

**Issue by rahulgavhar** [Avdhesh-Varshney/chanakya-niti#68]
With the help of cookies we can help the user to take him to the video till he watched (if the user doesnt remember or returns after a long time).

If the user decides to stay as guest without signing in. This can help him to stay up to date with his progress.

If he signup's as a user still the cookie will work with the customisation @ansh7432 is adding (the backend part)

**Comment by Avdhesh-Varshney** [comment]
@rahulgavhar move ahead. But join the project discord server. I will creating a meeting tomorrow to discuss the movement of this project ok.

**Comment by Avdhesh-Varshney** [comment]
@rahulgavhar Assigned to you.
