### ISSUE TITLE
 Add Card Component for Chanakya's History and Timeline

### ISSUE THREAD

**Issue by Akash4701** [Avdhesh-Varshney/chanakya-niti#74]
Objective:
Introduce a new card component to the project that provides users with a brief history and timeline of Chanakya, ensuring they have access to informative background details about Chanakya.

Details:
Component Name: ChanakyaHistoryCard
Description: This component will display a card with key historical information and a timeline of significant events related to Chanakya’s life. This addition aims to educate users about Chanakya’s background, contributions, and significance in history.
Implementation Steps:
Create the Card Component:
Develop a new React component named ChanakyaHistoryCard.
Use Bootstrap for styling to ensure a consistent look and feel with the rest of the application.
Structure the card to include:
A header with the title “Chanakya’s History and Timeline”.
A body section with brief paragraphs detailing Chanakya’s life, achievements, and important events.
Add Sample Content:

Include concise and informative text about Chanakya’s early life, education, key contributions, and notable events.
Use a timeline format to highlight significant milestones in Chanakya’s life.
Integrate the Component:

Import and include the ChanakyaHistoryCard component within the main application layout.

**This enhancement will provide users with valuable historical context about Chanakya, enriching their understanding and appreciation of the quotes and teachings displayed in the application.**

**Comment by Akash4701** [comment]
Please assign me for this issue @Avdhesh-Varshney  for SSoC-2024

**Comment by Avdhesh-Varshney** [comment]
Not required.
