### ISSUE TITLE
FEATURE Add

### ISSUE THREAD

**Issue by SDprogramer** [Avdhesh-Varshney/Chanakya-Niti#76]
![Screenshot 2024-06-05 132834](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/155221332/04015572-9858-4626-94e3-9ff03efe4206)

I want to add a cross button for every episode on upper right corner of the yellow image and then i want to add a speed increase button like normal 1.25x, 1.5x, 1.75x, 2x  etc. 

Please assign this issue to me

And currently i am under gssoc 24 and ssoc 24. Could you please assign these 2 label on this issue.

**Comment by Avdhesh-Varshney** [comment]
@SDprogramer issue already present #21 
only 1 open source program label is assigned to 1 issue.
