### ISSUE TITLE
Adding hamburger menu to show list of episodes

### ISSUE THREAD

**Issue by Anshikaa-Saini** [Avdhesh-Varshney/Chanakya-Niti#78]
I want to add a hamburger menu on the top left corner. It would contain a list of all episodes in the format:
episode 1 -> name of episode
episode 2 -> name of episode and so on 

It would appear like this:
![chanakya1](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/143860130/17033e9d-0adc-4f2e-95c5-19c6457fc37b)
![list](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/143860130/3a7dc259-a0e9-4701-801b-19d3d17950f3)

I want to work on this issue under SSoC label

**Comment by Avdhesh-Varshney** [comment]
@Anshikaa-Saini I am organizing a meeting tomorrow. So, join the project discord server and mention me about it for discussion purpose.

**Comment by Avdhesh-Varshney** [comment]
@Anshikaa-Saini not worked.
