### ISSUE TITLE
[Feature]: Improve video clip styling.

### ISSUE THREAD

**Issue by soniya-malviy** [Avdhesh-Varshney/chanakya-niti#79]
I can improve audio clip card which enhance user experience and betterment of website.

![Image 05-06-24 at 8 46 PM](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/151515611/9d255690-9e19-40e8-89b4-e47dcb8d8d05)

**Comment by Avdhesh-Varshney** [comment]
@soniya-malviy go ahead. But join the discord server, I will creating a meeting tomorrow. So, join it
