### ISSUE TITLE
[Feat]: Auto Commenting when an Issue is Closed

### ISSUE THREAD

**Issue by Asymtode712** [Avdhesh-Varshney/Chanakya-Niti#8]
This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

![issue closed](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/115717746/84f888c0-b9b7-4494-94aa-7f0e4fdf0a1b)

**Comment by Asymtode712** [comment]
@Avdhesh-Varshney please assign me this issue

**Comment by Avdhesh-Varshney** [comment]
@Asymtode712 this project is not required non-code things. So, just focus on the code not on non-code things.
