### ISSUE TITLE
[Feature]: Text in both Hindi and English

### ISSUE THREAD

**Issue by ISHITA1234** [Avdhesh-Varshney/Chanakya-Niti#83]
Hi, I would like to add both Hindi and English text to the website which will be helpful for multilingual population to access this website and would help a large number of population to be influenced by Chanakya's teachings.

I have suggested the following chnages.
![image](https://github.com/Avdhesh-Varshney/Chanakya-Niti/assets/32794324/4f799bd2-d92d-465a-b0eb-11332200b45d)

**Comment by ISHITA1234** [comment]
@Avdhesh-Varshney Please Assign this to me.

**Comment by Avdhesh-Varshney** [comment]
@ISHITA1234 Not required. This will distort the ui.
