### ISSUE TITLE
[Feature]: Adding playlist of videos with proper titles

### ISSUE THREAD

**Issue by ISHITA1234** [Avdhesh-Varshney/chanakya-niti#84]
Hi,
At present it is very difficult to know how many episodes are there. 
A new enhancement of adding all the video list with proper title for each video would be good to have.
This will help users know how many chapters(videos) are there and they can refer to any episodes by reading the video titles.

**Comment by Avdhesh-Varshney** [comment]
@ISHITA1234 I think this will increase the download load of the user. For further discussion, join the project discord channel.
