### ISSUE TITLE
adding contact us page frontend

### ISSUE THREAD

**Issue by Isha1233** [Avdhesh-Varshney/chanakya-niti#88]

**Comment by Isha1233** [comment]
@Avdhesh-Varshney  kindly assign this issue to me

**Comment by Avdhesh-Varshney** [comment]
@Isha1233 go ahead.

**Comment by Isha1233** [comment]
> @Isha1233 go ahead. Mention your open source program
@Avdhesh-Varshney  I'm not getting what's I need to mention

**Comment by Avdhesh-Varshney** [comment]
> > @Isha1233 go ahead. Mention your open source program
> > @Avdhesh-Varshney  I'm not getting what I need to mention

in which open source program are your participating? SSOC or GSSOC?

**Comment by Isha1233** [comment]
> > > @Isha1233 go ahead. Mention your open source program
> > > @Avdhesh-Varshney  I'm not getting what I need to mention
> 
> in which open source program are your participating? SSOC or GSSOC?

GSSOC
