### ISSUE TITLE
About Chanakya.

### ISSUE THREAD

**Issue by aapJoysakoi** [Avdhesh-Varshney/chanakya-niti#91]
Add an About section which includes basic brief about Chanakya, his teachings, his role in establishment of Maurya Empire and Chandragupta Maurya etc.

**Comment by aapJoysakoi** [comment]
Please assign me this issue as a part of SSOC.

**Comment by Avdhesh-Varshney** [comment]
@aapJoysakoi go ahead. But don't raise more than 1 issue at a time. Follow the guidelines for the next time.

**Comment by Saipradyumnagoud** [comment]
please assign me this issue under gssoc'24 
and label it under level 3

**Comment by Saipradyumnagoud** [comment]
please assign me this issue under gssoc'24 
and label it as gssoc And level 3

**Comment by Saipradyumnagoud** [comment]
please assign me under gssoc

**Comment by Avdhesh-Varshney** [comment]
@aapJoysakoi are you working on it?

**Comment by aapJoysakoi** [comment]
Yes, I am.

**Comment by Saipradyumnagoud** [comment]
@Avdhesh-Varshney  assign me under gssoc
