### ISSUE TITLE
[FEAT] 🧑‍💻: Shuffle Player Option in Audio Player Card

### ISSUE THREAD

**Issue by Atanu789** [Avdhesh-Varshney/chanakya-niti#96]
:red_circle: **Title** : Add Shuffle Player Option to Audio Player Card

:red_circle: **Enhancement Aim** : 
The aim of this enhancement is to introduce a shuffle option to the audio player card, allowing users to listen to audio tracks in a random order.

:red_circle: **Changes** : 

- Add a shuffle button to the audio player card UI.
- Implement the shuffle functionality in the audio player script.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Atanu Basak
- SSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Atanu789** [comment]
hey @Avdhesh-Varshney  kindly assign me this issue under SSOC'24

**Comment by Sneha0019** [comment]
Hello, @Avdhesh-Varshney Please assign me this task under Gssoc'24!
